#!/bin/sh
PORT=`basename $PWD`

echo "- Check for generic mistakes"
prtverify .

echo
echo "- Check for invalid files"
prtverify -m clean-repo .

echo
echo "- Check for missing dependencies"
prtverify -m missing-deps \
  -c /usr/ports/compat-32 \
  -c /usr/ports/contrib   \
  -c /usr/ports/core      \
  -c /usr/ports/opt       \
  -c /usr/ports/xorg      \
  $@ .

echo
echo "- Check for file-conflicts with other ports"
prtverify -m file-conflict \
  -c /usr/ports/compat-32 \
  -c /usr/ports/contrib   \
  -c /usr/ports/core      \
  -c /usr/ports/opt       \
  -c /usr/ports/xorg      \
  $@ .

echo
echo "- Check for linked dependencies"
if pkginfo -i | grep -q $PORT; then
  finddeps `basename $PWD` | cut -d' ' -f1 | sed -e '/\(glibc\|binutils\|gcc\)/d' | xargs
else
  echo "$PORT is not installed"
fi

echo
echo "- Check for redundant dependencies"
findredundantdeps -s `basename $PWD`

# vim:sw=2:ts=2:sts=2:et:cc=80
# End of file
